version: "3.10"

services:
  gateway:
    depends_on:
      - blueprints
      - users
    image: nginx
    volumes:
      - ./compose/gateway/nginx:/etc/nginx/
    ports:
      - "8080:80"
      - "8081:8081"

  blueprints:
    build:
      context: blueprints
    deploy:
      replicas: 2
    volumes:
      - ./blueprints/app:/opt/blueprints
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:
              severity:

  users:
    build:
      context: users
    volumes:
      - ./users/src:/opt/users
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./compose/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage

  loki:
    image: grafana/loki
    volumes:
      - ./compose/loki/loki-config.yaml:/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    command:
      - -config.file=/mnt/config/loki-config.yaml

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./compose/tempo/tempo-local.yaml:/etc/tempo.yaml
#      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest

  promtail:
    depends_on:
      - loki
    image: grafana/promtail:latest
    volumes:
      - /home/antonio/.docker_data/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml

  nginx-exporter:
    depends_on:
      - gateway
    image: nginx/nginx-prometheus-exporter:0.8.0
    command:
      - -nginx.scrape-uri
      - http://gateway/basic_status

  grafana:
    depends_on:
      - loki
      - prometheus
    image: grafana/grafana-oss
    volumes:
      - ./compose/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - "3000:3000"
    user: '104'

  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./compose/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  locust-worker:
    image: locustio/locust
    volumes:
      - ./compose/locust:/mnt/locust
    deploy:
      replicas: 2
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master