apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: observable-app
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  targetNamespace: pyday
  branch: main

  repo: "https://github.com/qustodio/observable-app-pyday"
  paths:
  - helm