# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: api
    honor_labels: true
    static_configs:
      - targets:
          - api:8000
        labels:
          job: api
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - localhost:9090