name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bumpversion:
    name: Create new version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump-version.outputs.new_ver }}
    steps:
      - uses: actions/checkout@v3
      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
      - name: Bump version and push tag
        uses: jaumann/github-bumpversion-action@v0.0.7
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Push tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          branch: main
      - run: |
          echo "Tag from git: $(git describe --abbrev=0 --tags)"
      - run: echo "🍏 This job's status is ${{ job.status }}."

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: v${{ needs.bumpversion.outputs.new_version }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file api/Dockerfile --tag aydevosotros/observable-api:${{ needs.bumpversion.outputs.new_version }}
    - name: Push the Docker image
      run: docker push aydevosotros/observable-api:${{ needs.bumpversion.outputs.new_version }}